const legal = {
  es: {
    notice: ['Aviso legal', 'Información general del sitio web y de su responsable.', [['Titular del sitio', 'Este sitio web pertenece a Luis Montes de Oca.'], ['Datos de contacto', 'Email: luismonteswebs@gmail.com · Madrid, España. Para cualquier consulta relacionada con este sitio, puedes escribir a la dirección indicada.'], ['Objeto', 'Este sitio tiene como finalidad presentar la actividad profesional, los proyectos y los servicios de desarrollo web de su titular.'], ['Propiedad intelectual', 'Los textos, diseños, código, imágenes y demás contenidos de este sitio están protegidos por la normativa aplicable. No se permite su reproducción o reutilización sin autorización previa, salvo los usos permitidos legalmente.'], ['Responsabilidad', 'El titular procura que la información publicada sea correcta y esté actualizada, pero no garantiza la ausencia de errores o la disponibilidad permanente del sitio.']]],
    privacy: ['Política de privacidad', 'Cómo se tratan los datos personales cuando contactas con este sitio.', [['Responsable', 'El responsable del tratamiento es Luis Montes de Oca. Puedes contactar en luismonteswebs@gmail.com.'], ['Datos tratados', 'Si utilizas el formulario de contacto, se pueden tratar tu nombre, dirección de email, motivo y el contenido del mensaje.'], ['Finalidad y base legal', 'Los datos se utilizan exclusivamente para responder a las consultas y gestionar una posible relación profesional. La base legal es tu consentimiento al enviar el formulario o escribir voluntariamente al email de contacto.'], ['Conservación', 'Los datos se conservarán durante el tiempo necesario para responder a la consulta y, posteriormente, durante los plazos exigidos por obligaciones legales o mientras puedan derivarse responsabilidades.'], ['Destinatarios y derechos', 'No se venderán tus datos ni se cederán a terceros salvo obligación legal o proveedores necesarios para prestar el servicio. Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad escribiendo a luismonteswebs@gmail.com. También puedes reclamar ante la Agencia Española de Protección de Datos.'], ['Seguridad', 'Se aplican medidas razonables para proteger la información, aunque ningún sistema conectado a Internet puede garantizar una seguridad absoluta.']]],
  },
  en: {
    notice: ['Legal notice', 'General information about this website and its owner.', [['Website owner', 'This website belongs to Luis Montes de Oca.'], ['Contact details', 'Email: luismonteswebs@gmail.com · Madrid, Spain. For any questions about this website, you can write to the address provided.'], ['Purpose', 'This website presents its owner’s professional work, projects and web development services.'], ['Intellectual property', 'The text, designs, code, images and other content on this website are protected by applicable law. Reproduction or reuse without prior permission is not allowed, except where legally permitted.'], ['Liability', 'The owner aims to keep published information accurate and up to date, but does not guarantee that it is error-free or that the website will always be available.']]],
    privacy: ['Privacy policy', 'How personal data is handled when you contact this website.', [['Controller', 'The data controller is Luis Montes de Oca. You can contact him at luismonteswebs@gmail.com.'], ['Data collected', 'If you use the contact form, your name, email address, reason for contact and message may be processed.'], ['Purpose and legal basis', 'Data is used solely to respond to enquiries and manage a potential professional relationship. The legal basis is your consent when submitting the form or voluntarily emailing the contact address.'], ['Retention', 'Data is kept for as long as needed to respond and afterwards for any periods required by law or while liabilities may arise.'], ['Recipients and rights', 'Your data will not be sold or shared except where legally required or with service providers needed to operate the website. You may request access, correction, deletion, objection, restriction or portability by emailing luismonteswebs@gmail.com. You may also lodge a complaint with the Spanish Data Protection Agency.'], ['Security', 'Reasonable measures are used to protect information, although no system connected to the internet can guarantee absolute security.']]],
  },
  fr: {
    notice: ['Mentions légales', 'Informations générales sur le site et son responsable.', [['Propriétaire du site', 'Ce site appartient à Luis Montes de Oca.'], ['Coordonnées', 'E-mail : luismonteswebs@gmail.com · Madrid, Espagne. Pour toute question concernant ce site, vous pouvez écrire à cette adresse.'], ['Objet', 'Ce site présente l’activité professionnelle, les projets et les services de développement web de son propriétaire.'], ['Propriété intellectuelle', 'Les textes, designs, codes, images et autres contenus de ce site sont protégés par la législation applicable. Toute reproduction ou réutilisation sans autorisation préalable est interdite, sauf exceptions prévues par la loi.'], ['Responsabilité', 'Le propriétaire s’efforce de publier des informations exactes et à jour, sans toutefois garantir l’absence d’erreurs ni la disponibilité permanente du site.']]],
    privacy: ['Politique de confidentialité', 'Traitement des données personnelles lorsque vous contactez ce site.', [['Responsable du traitement', 'Le responsable du traitement est Luis Montes de Oca. Vous pouvez le contacter à luismonteswebs@gmail.com.'], ['Données traitées', 'Si vous utilisez le formulaire de contact, votre nom, votre adresse e-mail, le motif et le contenu du message peuvent être traités.'], ['Finalité et base juridique', 'Les données servent uniquement à répondre aux demandes et à gérer une éventuelle relation professionnelle. La base juridique est votre consentement lorsque vous envoyez le formulaire ou un e-mail de votre propre initiative.'], ['Conservation', 'Les données sont conservées le temps nécessaire pour répondre, puis pendant les durées imposées par la loi ou tant que des responsabilités peuvent en découler.'], ['Destinataires et droits', 'Vos données ne sont ni vendues ni communiquées à des tiers, sauf obligation légale ou recours à des prestataires nécessaires au service. Vous pouvez demander l’accès, la rectification, l’effacement, l’opposition, la limitation ou la portabilité en écrivant à luismonteswebs@gmail.com. Vous pouvez également saisir l’Agence espagnole de protection des données.'], ['Sécurité', 'Des mesures raisonnables sont mises en œuvre pour protéger les informations, sans qu’aucun système connecté à Internet puisse garantir une sécurité absolue.']]],
  },
  de: {
    notice: ['Impressum', 'Allgemeine Informationen zu dieser Website und ihrem Betreiber.', [['Websitebetreiber', 'Diese Website gehört Luis Montes de Oca.'], ['Kontaktdaten', 'E-Mail: luismonteswebs@gmail.com · Madrid, Spanien. Bei Fragen zu dieser Website können Sie sich an die angegebene Adresse wenden.'], ['Zweck', 'Diese Website stellt die berufliche Tätigkeit, Projekte und Webentwicklungsleistungen des Betreibers vor.'], ['Urheberrecht', 'Texte, Designs, Code, Bilder und sonstige Inhalte dieser Website sind gesetzlich geschützt. Eine Vervielfältigung oder Wiederverwendung ohne vorherige Zustimmung ist untersagt, soweit dies nicht gesetzlich erlaubt ist.'], ['Haftung', 'Der Betreiber bemüht sich um korrekte und aktuelle Informationen, übernimmt jedoch keine Gewähr für Fehlerfreiheit oder dauerhafte Verfügbarkeit.']]],
    privacy: ['Datenschutzerklärung', 'Wie personenbezogene Daten verarbeitet werden, wenn Sie diese Website kontaktieren.', [['Verantwortlicher', 'Verantwortlicher ist Luis Montes de Oca. Sie erreichen ihn unter luismonteswebs@gmail.com.'], ['Verarbeitete Daten', 'Bei Nutzung des Kontaktformulars können Name, E-Mail-Adresse, Kontaktgrund und Nachrichteninhalt verarbeitet werden.'], ['Zweck und Rechtsgrundlage', 'Die Daten dienen ausschließlich der Beantwortung von Anfragen und der Anbahnung einer möglichen beruflichen Zusammenarbeit. Rechtsgrundlage ist Ihre Einwilligung beim Absenden des Formulars oder einer freiwilligen E-Mail.'], ['Speicherdauer', 'Die Daten werden so lange gespeichert, wie es zur Beantwortung erforderlich ist, und danach entsprechend gesetzlicher Pflichten oder möglicher Haftungsfristen.'], ['Empfänger und Rechte', 'Daten werden nicht verkauft oder weitergegeben, außer bei gesetzlicher Pflicht oder an notwendige Dienstleister. Sie können Auskunft, Berichtigung, Löschung, Widerspruch, Einschränkung oder Übertragbarkeit per E-Mail an luismonteswebs@gmail.com verlangen. Beschwerden sind bei der spanischen Datenschutzbehörde möglich.'], ['Sicherheit', 'Es werden angemessene Schutzmaßnahmen eingesetzt; absolute Sicherheit kann bei keinem mit dem Internet verbundenen System garantiert werden.']]],
  },
  gl: {
    notice: ['Aviso legal', 'Información xeral do sitio web e da persoa responsable.', [['Titular do sitio', 'Este sitio web pertence a Luis Montes de Oca.'], ['Datos de contacto', 'Correo: luismonteswebs@gmail.com · Madrid, España. Para calquera consulta sobre este sitio, podes escribir ao enderezo indicado.'], ['Obxecto', 'Este sitio presenta a actividade profesional, os proxectos e os servizos de desenvolvemento web do seu titular.'], ['Propiedade intelectual', 'Os textos, deseños, código, imaxes e demais contidos están protexidos pola normativa aplicable. Non se permite a súa reprodución ou reutilización sen autorización previa, agás nos usos permitidos legalmente.'], ['Responsabilidade', 'O titular procura que a información publicada sexa correcta e estea actualizada, pero non garante a ausencia de erros nin a dispoñibilidade permanente do sitio.']]],
    privacy: ['Política de privacidade', 'Como se tratan os datos persoais cando contactas con este sitio.', [['Responsable', 'A persoa responsable do tratamento é Luis Montes de Oca. Podes contactar en luismonteswebs@gmail.com.'], ['Datos tratados', 'Se utilizas o formulario de contacto, poden tratarse o teu nome, correo electrónico, motivo e contido da mensaxe.'], ['Finalidade e base legal', 'Os datos utilízanse unicamente para responder ás consultas e xestionar unha posible relación profesional. A base legal é o teu consentimento ao enviar o formulario ou escribir voluntariamente ao correo de contacto.'], ['Conservación', 'Os datos consérvanse o tempo necesario para responder e, despois, durante os prazos esixidos por obrigas legais ou mentres poidan derivarse responsabilidades.'], ['Destinatarios e dereitos', 'Non se venderán nin cederán os teus datos agás por obriga legal ou a provedores necesarios para prestar o servizo. Podes solicitar acceso, rectificación, supresión, oposición, limitación ou portabilidade escribindo a luismonteswebs@gmail.com. Tamén podes reclamar ante a Axencia Española de Protección de Datos.'], ['Seguridade', 'Aplícanse medidas razoables para protexer a información, aínda que ningún sistema conectado a Internet pode garantir unha seguridade absoluta.']]],
  },
  pt: {
    notice: ['Aviso legal', 'Informação geral sobre o website e a pessoa responsável.', [['Titular do website', 'Este website pertence a Luis Montes de Oca.'], ['Dados de contacto', 'Email: luismonteswebs@gmail.com · Madrid, Espanha. Para qualquer questão sobre este website, pode escrever para o endereço indicado.'], ['Objeto', 'Este website apresenta a atividade profissional, os projetos e os serviços de desenvolvimento web do seu titular.'], ['Propriedade intelectual', 'Os textos, designs, código, imagens e restantes conteúdos estão protegidos pela legislação aplicável. Não é permitida a sua reprodução ou reutilização sem autorização prévia, salvo nos casos legalmente permitidos.'], ['Responsabilidade', 'O titular procura manter a informação correta e atualizada, mas não garante a ausência de erros ou a disponibilidade permanente do website.']]],
    privacy: ['Política de privacidade', 'Como são tratados os dados pessoais quando contacta este website.', [['Responsável pelo tratamento', 'O responsável pelo tratamento é Luis Montes de Oca. Pode contactar através de luismonteswebs@gmail.com.'], ['Dados tratados', 'Ao utilizar o formulário de contacto, podem ser tratados o seu nome, email, motivo do contacto e conteúdo da mensagem.'], ['Finalidade e base legal', 'Os dados são utilizados exclusivamente para responder a pedidos e gerir uma possível relação profissional. A base legal é o seu consentimento ao enviar o formulário ou um email voluntário.'], ['Conservação', 'Os dados são conservados pelo tempo necessário para responder e, posteriormente, pelos prazos exigidos por lei ou enquanto puderem decorrer responsabilidades.'], ['Destinatários e direitos', 'Os dados não serão vendidos ou partilhados, exceto por obrigação legal ou com fornecedores necessários ao serviço. Pode solicitar acesso, retificação, apagamento, oposição, limitação ou portabilidade através de luismonteswebs@gmail.com. Pode também apresentar reclamação à Agência Espanhola de Proteção de Dados.'], ['Segurança', 'São aplicadas medidas razoáveis para proteger a informação, embora nenhum sistema ligado à Internet possa garantir segurança absoluta.']]],
  },
  ca: {
    notice: ['Avís legal', 'Informació general del lloc web i de la persona responsable.', [['Titular del lloc', 'Aquest lloc web pertany a Luis Montes de Oca.'], ['Dades de contacte', 'Correu: luismonteswebs@gmail.com · Madrid, Espanya. Per a qualsevol consulta sobre aquest lloc, pots escriure a l’adreça indicada.'], ['Objecte', 'Aquest lloc presenta l’activitat professional, els projectes i els serveis de desenvolupament web del seu titular.'], ['Propietat intel·lectual', 'Els textos, dissenys, codi, imatges i altres continguts estan protegits per la normativa aplicable. No se’n permet la reproducció o reutilització sense autorització prèvia, tret dels usos permesos legalment.'], ['Responsabilitat', 'El titular procura que la informació publicada sigui correcta i actualitzada, però no garanteix que no contingui errors ni la disponibilitat permanent del lloc.']]],
    privacy: ['Política de privacitat', 'Com es tracten les dades personals quan contactes amb aquest lloc.', [['Responsable', 'El responsable del tractament és Luis Montes de Oca. Pots contactar-hi a luismonteswebs@gmail.com.'], ['Dades tractades', 'Si fas servir el formulari de contacte, es poden tractar el teu nom, l’adreça electrònica, el motiu i el contingut del missatge.'], ['Finalitat i base legal', 'Les dades s’utilitzen exclusivament per respondre consultes i gestionar una possible relació professional. La base legal és el teu consentiment en enviar el formulari o escriure voluntàriament al correu de contacte.'], ['Conservació', 'Les dades es conserven el temps necessari per respondre i, posteriorment, durant els terminis exigits per obligacions legals o mentre se’n puguin derivar responsabilitats.'], ['Destinataris i drets', 'Les dades no es vendran ni cediran, excepte per obligació legal o a proveïdors necessaris per prestar el servei. Pots sol·licitar accés, rectificació, supressió, oposició, limitació o portabilitat escrivint a luismonteswebs@gmail.com. També pots reclamar davant l’Agència Espanyola de Protecció de Dades.'], ['Seguretat', 'S’apliquen mesures raonables per protegir la informació, tot i que cap sistema connectat a Internet pot garantir una seguretat absoluta.']]],
  },
}

export function getLegalContent(type, locale) {
  const language = legal[locale] ?? legal.es
  return type === '/politica-privacidad' ? language.privacy : language.notice
}
