const copy = {
  es: {
    'ferreteria-delicias': ['Ferretería Delicias', 'E-commerce', 'Participación en un proyecto de comercio electrónico para un negocio real, trabajando en diferentes aspectos técnicos, productos y optimización de contenido.', 'Online', 'Visitar web'],
    'la-luna-de-hugo': ['La Luna de Hugo', 'E-commerce', 'Desarrollo de una tienda online para un negocio real, trabajando en la experiencia, estructura y configuración de la plataforma de comercio electrónico.', 'Online', 'Visitar web'],
    'gestion-pedidos': ['Sistema de gestión de pedidos', 'Aplicación web', 'Aplicación web desarrollada para centralizar y facilitar la gestión de pedidos de una empresa.', 'Proyecto privado', 'Ver proyecto'],
    softgenio: ['Web corporativa SoftGenio', 'Web corporativa', 'Web corporativa premium y multidioma para SoftGenio S.L., consultoría y desarrollo de software: branding, contenido institucional y captación de leads con foco en autoridad, SEO y conversión.', 'Preview del proyecto', 'Ver proyecto'],
    'restaurante-gallego': ['Restaurante Gallego', 'Web para negocio', 'Web completa para un restaurante gallego: carta, galería, reservas, contacto por WhatsApp, multidioma, SEO avanzado y dark mode, con una identidad visual premium.', 'Preview del proyecto', 'Ver proyecto'],
  },
  en: {
    'ferreteria-delicias': ['Ferretería Delicias', 'E-commerce', 'Contributed to an online store for a real business, working on technical improvements, product content and optimisation.', 'Online', 'Visit website'],
    'la-luna-de-hugo': ['La Luna de Hugo', 'E-commerce', 'Built an online store for a real business, working on the user experience, structure and e-commerce platform setup.', 'Online', 'Visit website'],
    'gestion-pedidos': ['Order management system', 'Web application', 'A web application built to centralise and simplify a company’s order management.', 'Private project', 'View project'],
    softgenio: ['SoftGenio corporate website', 'Corporate website', 'A premium multilingual website for SoftGenio S.L., a software consultancy and development company, focused on brand authority, SEO and lead generation.', 'Project preview', 'View project'],
    'restaurante-gallego': ['Galician restaurant', 'Business website', 'A complete website for a Galician restaurant, featuring its menu, gallery, reservations, WhatsApp contact, multiple languages and advanced SEO.', 'Project preview', 'View project'],
  },
  de: {
    'ferreteria-delicias': ['Ferretería Delicias', 'E-Commerce', 'Mitarbeit an einem Online-Shop für ein reales Unternehmen mit Aufgaben in den Bereichen Technik, Produkte und Inhaltsoptimierung.', 'Online', 'Website besuchen'],
    'la-luna-de-hugo': ['La Luna de Hugo', 'E-Commerce', 'Entwicklung eines Online-Shops für ein reales Unternehmen mit Fokus auf Nutzererlebnis, Struktur und Einrichtung der E-Commerce-Plattform.', 'Online', 'Website besuchen'],
    'gestion-pedidos': ['Bestellverwaltungssystem', 'Webanwendung', 'Eine Webanwendung zur zentralen und einfachen Verwaltung der Bestellungen eines Unternehmens.', 'Privates Projekt', 'Projekt ansehen'],
    softgenio: ['SoftGenio-Unternehmenswebsite', 'Unternehmenswebsite', 'Eine mehrsprachige Premium-Website für SoftGenio S.L., eine Softwareberatung und -entwicklung, mit Fokus auf Markenautorität, SEO und Leadgenerierung.', 'Projektvorschau', 'Projekt ansehen'],
    'restaurante-gallego': ['Galicisches Restaurant', 'Website für ein Unternehmen', 'Eine umfassende Website für ein galicisches Restaurant mit Speisekarte, Galerie, Reservierungen, WhatsApp-Kontakt, mehreren Sprachen und erweitertem SEO.', 'Projektvorschau', 'Projekt ansehen'],
  },
  gl: {
    'ferreteria-delicias': ['Ferretería Delicias', 'Comercio electrónico', 'Colaboración nun proxecto de comercio electrónico para un negocio real, con tarefas técnicas, de produto e optimización de contidos.', 'En liña', 'Visitar web'],
    'la-luna-de-hugo': ['La Luna de Hugo', 'Comercio electrónico', 'Desenvolvemento dunha tenda en liña para un negocio real, traballando na experiencia, na estrutura e na configuración da plataforma.', 'En liña', 'Visitar web'],
    'gestion-pedidos': ['Sistema de xestión de pedidos', 'Aplicación web', 'Aplicación web creada para centralizar e facilitar a xestión dos pedidos dunha empresa.', 'Proxecto privado', 'Ver proxecto'],
    softgenio: ['Web corporativa de SoftGenio', 'Web corporativa', 'Web multilingüe premium para SoftGenio S.L., consultora e desenvolvedora de software, centrada na autoridade da marca, no SEO e na captación de clientes.', 'Vista previa do proxecto', 'Ver proxecto'],
    'restaurante-gallego': ['Restaurante galego', 'Web para negocio', 'Web completa para un restaurante galego con carta, galería, reservas, contacto por WhatsApp, varios idiomas e SEO avanzado.', 'Vista previa do proxecto', 'Ver proxecto'],
  },
  pt: {
    'ferreteria-delicias': ['Ferretería Delicias', 'Comércio eletrónico', 'Colaboração num projeto de comércio eletrónico para um negócio real, com trabalho técnico, de produto e otimização de conteúdos.', 'Online', 'Visitar website'],
    'la-luna-de-hugo': ['La Luna de Hugo', 'Comércio eletrónico', 'Desenvolvimento de uma loja online para um negócio real, com trabalho na experiência, estrutura e configuração da plataforma.', 'Online', 'Visitar website'],
    'gestion-pedidos': ['Sistema de gestão de encomendas', 'Aplicação web', 'Aplicação web criada para centralizar e simplificar a gestão de encomendas de uma empresa.', 'Projeto privado', 'Ver projeto'],
    softgenio: ['Website corporativo da SoftGenio', 'Website corporativo', 'Website premium e multilingue para a SoftGenio S.L., consultora e empresa de desenvolvimento de software, focado na marca, SEO e captação de potenciais clientes.', 'Pré-visualização do projeto', 'Ver projeto'],
    'restaurante-gallego': ['Restaurante galego', 'Website para negócio', 'Website completo para um restaurante galego, com menu, galeria, reservas, contacto por WhatsApp, vários idiomas e SEO avançado.', 'Pré-visualização do projeto', 'Ver projeto'],
  },
  ca: {
    'ferreteria-delicias': ['Ferretería Delicias', 'Comerç electrònic', 'Participació en un projecte de comerç electrònic per a un negoci real, amb tasques tècniques, de producte i d’optimització de continguts.', 'En línia', 'Visitar web'],
    'la-luna-de-hugo': ['La Luna de Hugo', 'Comerç electrònic', 'Desenvolupament d’una botiga en línia per a un negoci real, treballant en l’experiència, l’estructura i la configuració de la plataforma.', 'En línia', 'Visitar web'],
    'gestion-pedidos': ['Sistema de gestió de comandes', 'Aplicació web', 'Aplicació web creada per centralitzar i facilitar la gestió de comandes d’una empresa.', 'Projecte privat', 'Veure projecte'],
    softgenio: ['Web corporativa de SoftGenio', 'Web corporativa', 'Web multilingüe prèmium per a SoftGenio S.L., consultora i empresa de desenvolupament de programari, centrada en la marca, el SEO i la captació de clients potencials.', 'Vista prèvia del projecte', 'Veure projecte'],
    'restaurante-gallego': ['Restaurant gallec', 'Web per a negoci', 'Web completa per a un restaurant gallec amb carta, galeria, reserves, contacte per WhatsApp, diversos idiomes i SEO avançat.', 'Vista prèvia del projecte', 'Veure projecte'],
  },
  fr: {
    'ferreteria-delicias': ['Ferretería Delicias', 'E-commerce', 'Participation à la création d’une boutique en ligne pour une entreprise réelle, avec des missions techniques, produits et d’optimisation des contenus.', 'En ligne', 'Visiter le site'],
    'la-luna-de-hugo': ['La Luna de Hugo', 'E-commerce', 'Création d’une boutique en ligne pour une entreprise réelle, avec un travail sur l’expérience utilisateur, la structure et la configuration de la plateforme.', 'En ligne', 'Visiter le site'],
    'gestion-pedidos': ['Système de gestion des commandes', 'Application web', 'Application web conçue pour centraliser et simplifier la gestion des commandes d’une entreprise.', 'Projet privé', 'Voir le projet'],
    softgenio: ['Site institutionnel SoftGenio', 'Site institutionnel', 'Site multilingue haut de gamme pour SoftGenio S.L., société de conseil et de développement logiciel, axé sur la marque, le SEO et la génération de prospects.', 'Aperçu du projet', 'Voir le projet'],
    'restaurante-gallego': ['Restaurant galicien', 'Site pour entreprise', 'Site complet pour un restaurant galicien : menu, galerie, réservations, contact WhatsApp, plusieurs langues et SEO avancé.', 'Aperçu du projet', 'Voir le projet'],
  },
}

const details = {
  en: {
    'gestion-pedidos': { context: 'A B2B order-management platform for Awakelab, focused on service workflows, request validation, user roles, process automation and operational tracking.', project: ['A modern customer-facing order and service platform with a robust internal administration backend. Users can register, create service requests, check training availability and track each request.', 'Includes authentication, roles, company and department management, business workflows, course catalogues, data validation and approval processes.'], features: ['User registration and sign-in with different roles', 'Company, department, customer and role management', 'Service-based order creation', 'Training and content availability', 'Request validation and approval workflow'], goal: 'Provide a scalable operational platform for managing complex orders in a corporate environment.', status: 'Private project' },
    softgenio: { context: ['Premium corporate website for SoftGenio S.L., a software consultancy and development company seeking a strong position in Spain and international markets.', 'Combines brand strategy, corporate content and lead generation to communicate services and success stories, improve organic visibility and turn visits into business opportunities.'], project: ['A modern multilingual website designed to build trust and generate leads, with a clear presentation of the company, its methods, results and expertise.', 'Includes advanced SEO architecture, responsive design, dark mode and a modular structure ready to grow.'], features: ['Homepage with value proposition, services, results and calls to action', 'Service pages with benefits and differentiators', 'Company process, story, vision and mission', 'Success stories and project results', 'Contact forms and direct WhatsApp links', 'Localised Spanish and English routes with SEO', 'Validated forms using React Hook Form and Zod', 'Technical SEO, metadata, hreflang, sitemap and structured data'], goal: 'Position SoftGenio as a trusted technology consultancy and increase qualified leads with a premium desktop and mobile experience.', status: 'Project preview' },
    'restaurante-gallego': { context: 'A complete website for a real restaurant, focused on brand identity, reservations, SEO and multiple languages. It includes the home page, menu, food and venue gallery, restaurant story and legal pages.', project: 'A modern restaurant website with a premium Sargadelos-inspired cobalt-blue identity, multilingual content, reservations, WhatsApp contact, advanced SEO, dark mode and responsive design. Includes validated forms, booking links, structured metadata, testing and Cloudflare deployment.', features: ['Homepage with testimonials, team, gallery and reservation calls to action', 'Menu with category navigation', 'Gallery of dishes and venue', 'Restaurant story and brand proposition', 'Contact and reservation forms with WhatsApp links', 'Spanish, Galician, English and Portuguese routes', 'SEO metadata, sitemap and structured data', 'Dark mode, responsive design and accessibility enhancements'], goal: 'Present the restaurant with a distinctive premium identity and make it easy for visitors to explore the menu and book a table.', status: 'Project preview' },
  },
  fr: {
    'gestion-pedidos': { context: 'Plateforme B2B de gestion des commandes pour Awakelab, axée sur les workflows de services, la validation des demandes, les rôles, l’automatisation et le suivi opérationnel.', project: ['Une plateforme moderne pour les clients, associée à un backend d’administration interne robuste. Elle permet de créer des demandes de service, de consulter les formations disponibles et de suivre chaque demande.', 'Le projet comprend l’authentification, les rôles, la gestion des entreprises et services, les workflows métier, les catalogues de cours, la validation et les processus d’approbation.'], features: ['Inscription et connexion avec plusieurs rôles', 'Gestion des entreprises, services, clients et rôles', 'Création de commandes par type de service', 'Consultation des contenus et formations disponibles', 'Validation et approbation des demandes'], goal: 'Fournir une solution évolutive pour gérer des commandes complexes en entreprise.', status: 'Projet privé' },
    softgenio: { context: ['Site institutionnel haut de gamme pour SoftGenio S.L., société de conseil et de développement logiciel souhaitant renforcer sa présence en Espagne et à l’international.', 'Le site associe stratégie de marque, contenu institutionnel et génération de prospects afin de présenter les services, améliorer le référencement et transformer les visites en opportunités.'], project: ['Site moderne et multilingue conçu pour inspirer confiance et générer des prospects, avec une présentation claire de l’entreprise, de sa méthode et de ses résultats.', 'Comprend une architecture SEO avancée, un design responsive, un mode sombre et une structure modulaire évolutive.'], features: ['Page d’accueil avec proposition de valeur, services et appels à l’action', 'Pages de services présentant avantages et différenciateurs', 'Présentation de la méthode, de l’histoire et de la mission', 'Études de cas et résultats de projets', 'Formulaires de contact et liens WhatsApp', 'Parcours localisés en espagnol et en anglais', 'Formulaires validés avec React Hook Form et Zod', 'SEO technique, métadonnées, hreflang et données structurées'], goal: 'Positionner SoftGenio comme une société technologique fiable et développer les demandes qualifiées grâce à une expérience haut de gamme.', status: 'Aperçu du projet' },
    'restaurante-gallego': { context: 'Site complet pour un restaurant réel, axé sur l’identité de marque, les réservations, le SEO et le multilinguisme. Il comprend la page d’accueil, le menu, une galerie et des pages légales.', project: 'Site moderne à l’identité premium inspirée de Sargadelos, avec contenu multilingue, réservations, contact WhatsApp, SEO avancé, mode sombre et design responsive. Les formulaires sont validés et les réservations sont reliées à des services externes.', features: ['Page d’accueil avec témoignages, équipe et réservations', 'Menu avec navigation par catégories', 'Galerie des plats et du restaurant', 'Présentation de l’histoire et de l’identité du restaurant', 'Formulaires de contact et de réservation avec WhatsApp', 'Parcours en espagnol, galicien, anglais et portugais', 'Métadonnées SEO, sitemap et données structurées', 'Mode sombre, design responsive et améliorations d’accessibilité'], goal: 'Valoriser l’identité du restaurant et faciliter la découverte du menu et la réservation d’une table.', status: 'Aperçu du projet' },
  },
  de: {
    'gestion-pedidos': { context: 'B2B-Plattform zur Auftragsverwaltung für Awakelab mit Fokus auf Serviceabläufe, Antragsprüfung, Benutzerrollen, Automatisierung und Fortschrittskontrolle.', project: ['Moderne Oberfläche für Kunden mit robustem internen Administrations-Backend. Nutzer können Anfragen erstellen, Schulungen prüfen und den Bearbeitungsstand verfolgen.', 'Enthält Anmeldung, Rollen, Unternehmens- und Abteilungsverwaltung, Geschäftsabläufe, Kurskataloge, Datenprüfung und Freigaben.'], features: ['Registrierung und Anmeldung mit verschiedenen Rollen', 'Verwaltung von Unternehmen, Abteilungen und Kunden', 'Aufträge nach Servicetyp erstellen', 'Verfügbarkeit von Schulungen prüfen', 'Prüfungs- und Freigabeprozess für Anfragen'], goal: 'Eine skalierbare Lösung zur Verwaltung komplexer Unternehmensaufträge schaffen.', status: 'Privates Projekt' },
    softgenio: { context: ['Hochwertige Unternehmenswebsite für SoftGenio S.L., eine Softwareberatung und -entwicklung mit Ambitionen in Spanien und internationalen Märkten.', 'Die Website verbindet Markenstrategie, Unternehmensinhalte und Leadgenerierung, um Leistungen zu vermitteln, die organische Sichtbarkeit zu verbessern und Geschäftsanfragen zu gewinnen.'], project: ['Eine moderne mehrsprachige Website, die Vertrauen schafft und Anfragen fördert, mit einer klaren Darstellung des Unternehmens und seiner Arbeitsweise.', 'Mit fortgeschrittener SEO-Struktur, responsivem Design, Dark Mode und modularer Architektur.'], features: ['Startseite mit Wertversprechen, Leistungen und Handlungsaufforderungen', 'Leistungsseiten mit Vorteilen und Besonderheiten', 'Einblicke in Arbeitsweise, Geschichte und Mission', 'Erfolgsgeschichten und Projektergebnisse', 'Kontaktformulare und direkte WhatsApp-Links', 'Lokalisierte spanische und englische Seiten', 'Validierte Formulare mit React Hook Form und Zod', 'Technisches SEO, Metadaten, hreflang und strukturierte Daten'], goal: 'SoftGenio als vertrauenswürdige Technologieberatung positionieren und qualifizierte Anfragen gewinnen.', status: 'Projektvorschau' },
    'restaurante-gallego': { context: 'Umfassende Website für ein echtes Restaurant mit Fokus auf Marke, Reservierungen, SEO und Mehrsprachigkeit. Enthalten sind Startseite, Speisekarte, Galerie und rechtliche Seiten.', project: 'Moderne Restaurant-Website mit hochwertiger, von Sargadelos inspirierter kobaltblauer Markenidentität, mehreren Sprachen, Reservierungen, WhatsApp-Kontakt, SEO, Dark Mode und responsivem Design.', features: ['Startseite mit Team, Galerie und Reservierungsaufrufen', 'Speisekarte mit Kategorienavigation', 'Galerie mit Speisen und Restaurant', 'Geschichte und Markenauftritt des Restaurants', 'Kontakt- und Reservierungsformulare mit WhatsApp', 'Spanische, galicische, englische und portugiesische Seiten', 'SEO-Metadaten, Sitemap und strukturierte Daten', 'Dark Mode, responsives Design und Barrierefreiheit'], goal: 'Die hochwertige Identität des Restaurants präsentieren und Menüansicht sowie Reservierungen erleichtern.', status: 'Projektvorschau' },
  },
  gl: {
    'gestion-pedidos': { context: 'Plataforma B2B de xestión de pedidos para Awakelab, centrada nos fluxos de servizos, validación de solicitudes, roles, automatización e seguimento operativo.', project: ['Plataforma moderna para clientes cun backend robusto de administración interna. Permite crear solicitudes, consultar formación dispoñible e seguir o estado de cada pedido.', 'Inclúe autenticación, roles, xestión de empresas e departamentos, fluxos de negocio, catálogos de cursos, validación e aprobación.'], features: ['Rexistro e acceso con distintos roles', 'Xestión de empresas, departamentos e clientes', 'Creación de pedidos por tipo de servizo', 'Consulta de contidos e formación dispoñibles', 'Validación e aprobación de solicitudes'], goal: 'Ofrecer unha solución escalable para xestionar pedidos complexos nunha contorna empresarial.', status: 'Proxecto privado' },
    softgenio: { context: ['Web corporativa premium para SoftGenio S.L., consultora e empresa de desenvolvemento de software con presenza en España e mercados internacionais.', 'Combina estratexia de marca, contido corporativo e captación de clientes para comunicar servizos, mellorar a visibilidade orgánica e xerar oportunidades.'], project: ['Web moderna e multilingüe para transmitir confianza e captar clientes, cunha presentación clara da empresa, do seu método e dos seus resultados.', 'Inclúe arquitectura SEO avanzada, deseño adaptable, modo escuro e estrutura modular.'], features: ['Inicio con proposta de valor, servizos e chamadas á acción', 'Páxinas de servizos con beneficios e diferenzas', 'Metodoloxía, historia e misión da empresa', 'Casos de éxito e resultados', 'Formularios de contacto e ligazóns a WhatsApp', 'Rutas en español e inglés', 'Formularios validados con React Hook Form e Zod', 'SEO técnico, metadatos, hreflang e datos estruturados'], goal: 'Situar SoftGenio como unha consultora tecnolóxica de confianza e aumentar as solicitudes cualificadas.', status: 'Vista previa do proxecto' },
    'restaurante-gallego': { context: 'Web completa para un restaurante real, centrada na marca, nas reservas, no SEO e nos idiomas. Inclúe inicio, carta, galería e páxinas legais.', project: 'Web moderna cunha identidade premium inspirada en Sargadelos, contido en varios idiomas, reservas, contacto por WhatsApp, SEO avanzado, modo escuro e deseño adaptable.', features: ['Inicio con equipo, galería e chamadas para reservar', 'Carta con navegación por categorías', 'Galería de pratos e do local', 'Historia e identidade do restaurante', 'Formularios de contacto e reserva con WhatsApp', 'Contido en español, galego, inglés e portugués', 'Metadatos SEO, sitemap e datos estruturados', 'Modo escuro, deseño adaptable e melloras de accesibilidade'], goal: 'Presentar a identidade do restaurante e facilitar a consulta da carta e as reservas.', status: 'Vista previa do proxecto' },
  },
  pt: {
    'gestion-pedidos': { context: 'Plataforma B2B de gestão de encomendas para a Awakelab, focada nos fluxos de serviço, validação de pedidos, funções de utilizador, automatização e acompanhamento operacional.', project: ['Plataforma moderna para clientes com um backend robusto de administração interna. Permite criar pedidos, consultar formação disponível e acompanhar o estado de cada solicitação.', 'Inclui autenticação, funções, gestão de empresas e departamentos, fluxos de negócio, catálogos de cursos, validação e aprovação.'], features: ['Registo e início de sessão com diferentes funções', 'Gestão de empresas, departamentos e clientes', 'Criação de encomendas por tipo de serviço', 'Consulta de conteúdos e formação disponíveis', 'Validação e aprovação de pedidos'], goal: 'Disponibilizar uma solução escalável para gerir encomendas complexas em contexto empresarial.', status: 'Projeto privado' },
    softgenio: { context: ['Website corporativo premium para a SoftGenio S.L., consultora e empresa de desenvolvimento de software com ambição nos mercados espanhol e internacional.', 'Combina estratégia de marca, conteúdos institucionais e captação de potenciais clientes para apresentar serviços, melhorar a visibilidade orgânica e gerar oportunidades.'], project: ['Website moderno e multilingue, concebido para transmitir confiança e gerar contactos, com uma apresentação clara da empresa e dos seus métodos.', 'Inclui arquitetura SEO avançada, design responsivo, modo escuro e estrutura modular.'], features: ['Página inicial com proposta de valor, serviços e chamadas à ação', 'Páginas de serviços com benefícios e diferenciação', 'Metodologia, história e missão da empresa', 'Casos de sucesso e resultados', 'Formulários de contacto e ligações diretas ao WhatsApp', 'Páginas em espanhol e inglês', 'Formulários validados com React Hook Form e Zod', 'SEO técnico, metadados, hreflang e dados estruturados'], goal: 'Posicionar a SoftGenio como consultora tecnológica de confiança e aumentar os contactos qualificados.', status: 'Pré-visualização do projeto' },
    'restaurante-gallego': { context: 'Website completo para um restaurante real, focado na marca, nas reservas, no SEO e nos idiomas. Inclui página inicial, menu, galeria e páginas legais.', project: 'Website moderno com identidade premium inspirada em Sargadelos, conteúdos multilingues, reservas, contacto por WhatsApp, SEO avançado, modo escuro e design responsivo.', features: ['Página inicial com equipa, galeria e chamadas para reserva', 'Menu com navegação por categorias', 'Galeria de pratos e do espaço', 'História e identidade do restaurante', 'Formulários de contacto e reserva com WhatsApp', 'Conteúdos em espanhol, galego, inglês e português', 'Metadados SEO, sitemap e dados estruturados', 'Modo escuro, design responsivo e melhorias de acessibilidade'], goal: 'Apresentar a identidade do restaurante e facilitar a consulta do menu e as reservas.', status: 'Pré-visualização do projeto' },
  },
  ca: {
    'gestion-pedidos': { context: 'Plataforma B2B de gestió de comandes per a Awakelab, centrada en fluxos de servei, validació de sol·licituds, rols, automatització i seguiment operatiu.', project: ['Plataforma moderna per als clients amb un backend robust d’administració interna. Permet crear sol·licituds, consultar formacions disponibles i seguir cada comanda.', 'Inclou autenticació, rols, gestió d’empreses i departaments, fluxos de negoci, catàlegs de cursos, validació i aprovació.'], features: ['Registre i inici de sessió amb diversos rols', 'Gestió d’empreses, departaments i clients', 'Creació de comandes per tipus de servei', 'Consulta de continguts i formacions disponibles', 'Validació i aprovació de sol·licituds'], goal: 'Oferir una solució escalable per gestionar comandes complexes en una empresa.', status: 'Projecte privat' },
    softgenio: { context: ['Web corporativa prèmium per a SoftGenio S.L., consultora i empresa de desenvolupament de programari amb presència a Espanya i mercats internacionals.', 'Combina estratègia de marca, contingut corporatiu i captació de clients per comunicar serveis, millorar la visibilitat orgànica i generar oportunitats.'], project: ['Web moderna i multilingüe per transmetre confiança i captar contactes, amb una presentació clara de l’empresa i la seva manera de treballar.', 'Inclou arquitectura SEO avançada, disseny adaptable, mode fosc i estructura modular.'], features: ['Inici amb proposta de valor, serveis i crides a l’acció', 'Pàgines de serveis amb beneficis i diferenciadors', 'Metodologia, història i missió de l’empresa', 'Casos d’èxit i resultats', 'Formularis de contacte i enllaços directes a WhatsApp', 'Pàgines en castellà i anglès', 'Formularis validats amb React Hook Form i Zod', 'SEO tècnic, metadades, hreflang i dades estructurades'], goal: 'Posicionar SoftGenio com una consultora tecnològica de confiança i augmentar els contactes qualificats.', status: 'Vista prèvia del projecte' },
    'restaurante-gallego': { context: 'Web completa per a un restaurant real, centrada en la marca, les reserves, el SEO i els idiomes. Inclou inici, carta, galeria i pàgines legals.', project: 'Web moderna amb una identitat prèmium inspirada en Sargadelos, contingut multilingüe, reserves, contacte per WhatsApp, SEO avançat, mode fosc i disseny adaptable.', features: ['Inici amb equip, galeria i crides a reservar', 'Carta amb navegació per categories', 'Galeria de plats i de l’espai', 'Història i identitat del restaurant', 'Formularis de contacte i reserva amb WhatsApp', 'Contingut en castellà, gallec, anglès i portuguès', 'Metadades SEO, sitemap i dades estructurades', 'Mode fosc, disseny adaptable i millores d’accessibilitat'], goal: 'Presentar la identitat del restaurant i facilitar la consulta de la carta i les reserves.', status: 'Vista prèvia del projecte' },
  },
  es: {
    'gestion-pedidos': { status: 'Proyecto privado' },
    softgenio: { context: ['Web corporativa premium de SoftGenio S.L., especializada en consultoría y desarrollo de software.', 'Combina estrategia comercial, branding, contenido institucional y captación de leads para reforzar la marca, mejorar el SEO y generar oportunidades.'], project: ['Web moderna y multidioma para transmitir confianza y facilitar la captación de leads.', 'Incluye arquitectura SEO avanzada, diseño responsive, dark mode y estructura modular.'], features: ['Página principal con propuesta de valor, servicios y llamadas a la acción', 'Páginas de servicios con beneficios y diferenciadores', 'Proceso de trabajo, historia y misión de la empresa', 'Casos de éxito y resultados', 'Formularios de contacto y enlaces a WhatsApp', 'Rutas localizadas en español e inglés', 'Formularios validados con React Hook Form y Zod', 'SEO técnico, metadata, hreflang y datos estructurados'], goal: 'Posicionar a SoftGenio como una consultora tecnológica de confianza y aumentar los leads cualificados.', status: 'Preview del proyecto' },
    'restaurante-gallego': { context: 'Web completa para un restaurante real, orientada a marca, reservas, SEO y multidioma. Incluye página principal, carta, galería, historia y páginas legales.', project: 'Web moderna con identidad premium inspirada en Sargadelos, multidioma, reservas, contacto por WhatsApp, SEO avanzado, dark mode y diseño responsive.', features: ['Página principal con equipo, galería y llamadas a reservar', 'Carta con navegación por categorías', 'Galería de platos y del restaurante', 'Historia e identidad del restaurante', 'Formularios de contacto y reserva con WhatsApp', 'Contenido en español, gallego, inglés y portugués', 'Metadata SEO, sitemap y datos estructurados', 'Dark mode, diseño responsive y mejoras de accesibilidad'], goal: 'Presentar la identidad del restaurante y facilitar la consulta de la carta y las reservas.', status: 'Preview del proyecto' },
  },
}

export function localizeProject(project, locale) {
  const values = copy[locale]?.[project.slug] ?? copy.es[project.slug]
  if (!values) return project
  const [title, category, description, statusLabel, cta] = values
  const localizedDetails = details[locale]?.[project.slug] ?? details.es[project.slug]
  return {
    ...project,
    title,
    category,
    description,
    statusLabel,
    cta,
    ...(project.details && localizedDetails ? { details: { ...project.details, ...localizedDetails } } : {}),
  }
}
